### ISSUE TITLE
Possible Bug: currentUser on Auth should be a Future

### ISSUE THREAD

**Issue by dev-mush** [FirebaseExtended/firebase-dart#210]
* **Dart Version**
`Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"`
* **OS Version**
`Mac OS X 10.14.3 build: 18D109`
* **Firebase Package** 
```
  firebase:
    git:
      url: https://github.com/FirebaseExtended/firebase-dart
```

I've been running in a very peculiar issue, I've had to implement this behaviour: if the current user is null, enforce an anonymous sign in.
The problem is that `currentUser` on `Auth` is temporarily null after `Auth` is initialized, and becomes populated after a while.
I've solved this problem on flutter rather easily because the `currentUser` is a Future, but on this package it is a sync instance which doesn't reflect the real value of the data stored on disk (at initialization time). I've implemented a workaround by having a 1 second sleep timer to give time to the library to initialise, but It's not ideal.

I'd be glad to contribute and open a PR to fix this, but since I'm fairly new to Dart and js interop and I'm really short on time, is it possible to have some hints on how it works and what I should be looking into?

**Comment by A-Babin** [comment]
That's how the underlying Javascript API is designed. [`Auth.currentUser`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth.html#current-user) gives you just the `User` or null, not a promise. 

That said, the first value that comes through `Auth.onAuthStateChanged` should be all that you need. It will be the `User` if the client is already signed in, and it will be null otherwise. So, (_as long as you await it before  `Auth` initializes_) you can get a `Future` from `authRef.onAuthStateChanged.first` that should do exactly what you want, and it's very idiomatic Dart.

**Comment by Michael77** [comment]
Would it be possible to have the currentUser return a promise for a v7 release? I would be happy to implement the change.

**Comment by kevmoo** [comment]
Would be possible, I think. PRs welcome

**Comment by kevmoo** [comment]
This package is meant to be a relatively thin wrapper over the JS api.

I get the idea, but going to close it out.
