### ISSUE TITLE
FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined

### ISSUE THREAD

**Issue by aryzhov** [FirebaseExtended/firebase-dart#224]
I am getting an exception when using the `firebase` package in a Flutter Web application. The exception occurs only when the app is compiled using `webdev build` and can be seen in the browser console:

```
Uncaught FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined
    at new t (https://www.gstatic.com/firebasejs/5.9.2/firebase-firestore.js:1:53740)
    at r.createError (https://www.gstatic.com/firebasejs/5.9.2/firebase-firestore.js:1:316869)
    at t.parseScalarValue (https://www.gstatic.com/firebasejs/5.9.2/firebase-firestore.js:1:322296)
    at t.parseData (https://www.gstatic.com/firebasejs/5.9.2/firebase-firestore.js:1:320197)
    at https://www.gstatic.com/firebasejs/5.9.2/firebase-firestore.js:1:320372
    at Nn (https://www.gstatic.com/firebasejs/5.9.2/firebase-firestore.js:1:54403)
    at t.parseObject (https://www.gstatic.com/firebasejs/5.9.2/firebase-firestore.js:1:320345)
    at t.parseData (https://www.gstatic.com/firebasejs/5.9.2/firebase-firestore.js:1:319946)
    at t.parseArray (https://www.gstatic.com/firebasejs/5.9.2/firebase-firestore.js:1:320547)
    at t.parseData (https://www.gstatic.com/firebasejs/5.9.2/firebase-firestore.js:1:320169)
```
The exception occurs at the following line in my code:
```
    await docRef.set(changes, SetOptions(merge: true));
```
where `changes` is a `Map<string, dynamic>`. 

## Diagnosis

With the in-browser debugger I have found that some of the values in `changes` are indeed `undefined`, while some other values are `null`. The first `undefined` value in the map causes the exception. Why does dart2js sometimes translate `null` values to `undefined`? I found the ticket that answers this question: [dart2js functions sometimes return undefined instead of null](https://github.com/dart-lang/sdk/issues/27485). The ticket has been open for 2 years now and it does not look like it will be resolved soon. 

## Workaround

The aforementioned dart2js ticket prescribes a workaround to ensure that the stored value is `null` and not `undefined`. I expanded on that idea and created a function that takes a `Map` object and converts all `undefined` values to `null`:

```dart
import 'dart:js';

final _null = (() => new JsObject.jsify({'a': null})['a'])();

T sanitize<T>(T value) {
  if(value == null) {
    return _null;
  } else if(value is Map) {
    return Map<String, dynamic>.fromEntries(value.entries.map((me) => MapEntry(me.key, sanitize(me.value)))) as T;
  } else if(value is List) {
    return value.map((el) => sanitize(el)).toList() as T;
  } else {
    return value;
  }
}
```
I applied the workaround to the line that threw the exception as follows:
```dart
    final sanitized = sanitize(changes);
    await docRef.set(sanitized, SetOptions(merge: true));
```
With this workaround, the exception is gone.

## Fix options

I can see two options for fixing this issue:

1. Embed the `sanitize()` functionality into `firebase-dart` package by sanitizing the input map before sending it to the underlying `firebase.js`. Feel free to take this code or write a better optimized code.
2. Change `firebase.js` to treat `undefined` values as nulls instead of throwing an exception.

## Environment

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E227, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)
```

pubspec.lock
```
  firebase:
    dependency: "direct main"
    description:
      name: firebase
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.3"
```

**Comment by thherman** [comment]
Thank you for the workaround.
I don't get why this is still not fixed.

**Comment by MarioHit** [comment]
I had the same error, **_I had misspelled a prop name ('Id:'instead of 'id:')_** while defining my product, so just changed it to 'id' and it worked !

(once it was fixed i tested whithout the id , and i had the same error again so you you should check i you are not missing any prop or field name in one of your items ) 

log : 
`

Unhandled Rejection (FirebaseError): Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in document users/sTSjmxB3L7YmwjmMJc4xkzsWXjF3/orders/pi_1HTcOaGcERsAUsytD1Kfqilf)
▼ 18 stack frames were expanded.
new n
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:129
Cu
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13957
t.h_
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13682
(anonymous function)
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13885
Lu
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13886
(anonymous function)
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13895
_
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:306
Ru
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13894
Lu
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13796
(anonymous function)
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13827
Lu
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13840
(anonymous function)
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13895
_
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:306
Ru
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13894
Du
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13723
n.set
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:15312
(anonymous function)
C:/Users/***$$$***/src/Payment.js:57
async handleSubmit
C:/Users/***$$$***/src/Payment.js:49
▲ 18 stack frames were expanded.`

**Comment by MarioHit** [comment]
I had the same error (on one of my projects) , **_I had misspelled a prop name ('Id:'instead of 'id:')_** while defining my product, so I just changed it to 'id' and it worked !


(once it was fixed I tested without the id or another field : same error again so you should check if you are not missing any prop or field name in one of your items)

log : 
`

Unhandled Rejection (FirebaseError): Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in document "***path to document*** ")
▼ 18 stack frames were expanded.
new n
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:129
Cu
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13957
t.h_
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13682
(anonymous function)
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13885
Lu
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13886
(anonymous function)
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13895
_
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:306
Ru
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13894
Lu
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13796
(anonymous function)
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13827
Lu
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13840
(anonymous function)
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13895
_
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:306
Ru
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13894
Du
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:13723
n.set
C:/Users/***$$$***/node_modules/@firebase/firestore/dist/index.cjs.js:15312
(anonymous function)
C:/Users/***$$$***/src/Payment.js:57
async handleSubmit
C:/Users/***$$$***/src/Payment.js:49
▲ 18 stack frames were expanded.`

**Comment by kevmoo** [comment]
I this this is fixed now with how we detect objects.
